name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Postman collection with Newman
        run: newman run ./postman/collections/Users/.resources/Users.postman_collection.json -e ./postman/collections/Users/.resources/enviromentServeRest.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export ./postman/reports/reportsServeRest.html

      - name: Upload Newman report
        uses: actions/upload-artifact@v6
        with:
          name: Test Report
          path: repreportsServeRest.html